FROM jenkins/jenkins:lts-jdk25

USER root

RUN apt-get update && \
    apt-get install -y docker.io maven && \
    apt-get clean

RUN groupmod -g 989 docker && \
    usermod -aG docker jenkins

USER jenkins